#!/bin/bash
pip install pipenv
pipenv install --dev &
git submodule update --init
cd z3_source
mkdir -p build
cd build
cmake -D BUILD_PYTHON_BINDINGS:BOOL=ON -D INSTALL_PYTHON_BINDINGS:BOOL=OFF ..
make -j $(nproc)
cd ../..
wait
make
