#!/usr/bin/tclsh

set tests [glob "cli_tests/*/*.exp"]
puts "1..[llength $tests]"
foreach test $tests {
  set result {}
  try {
    exec expect $test
    puts "ok([file tail $test])"
  } trap {} {output state} {
    puts "Caught error:"
    puts $output
    exit 2
  }
  #>@ stdout 2>@ stderr
}
