source "./testing.tcl"
file delete complex_test.py
spawn poetry run testbuilder --no-color --unroll-depth=10 --lines=2,8,12 complex.py

expect -re {\{.*: ([-\d]+), .*: ([-\d]+)\}.*expected}
set value [expr $expect_out(1,string) * $expect_out(2,string)]
send -- "$value\n"
expect "Couldn't generate a test for line 8"
expect expected
send "None\n"
system pytest complex_test.py
file delete complex_test.py
